// DO NOT EDIT THIS FILE
// This file is automatically generated from the webgme-setup-tool.
'use strict';


var config = require('webgme/config/config.default'),
    validateConfig = require('webgme/config/validator');

// The paths can be loaded from the webgme-setup.json
config.plugin.basePaths.push(__dirname + '/../src/plugins');
config.plugin.basePaths.push(__dirname + '/../node_modules/webgme-icore/src/plugins');
config.seedProjects.basePaths.push(__dirname + '/../src/seeds/StateMachine');
config.seedProjects.basePaths.push(__dirname + '/../src/seeds/PetriNet');



config.visualization.panelPaths.push(__dirname + '/../src/visualizers/panels');




// Visualizer descriptors
config.visualization.visualizerDescriptors.push(__dirname + '/../src/visualizers/Visualizers.json');
// Add requirejs paths
config.requirejsPaths = {
  'PyCoreExecutor': 'node_modules/webgme-icore/src/plugins/PyCoreExecutor',
  'panels': './src/visualizers/panels',
  'widgets': './src/visualizers/widgets',
  'webgme-icore': './node_modules/webgme-icore/src/common',
  'statemachinejoint': './src/common'
};


config.mongo.uri = 'mongodb://127.0.0.1:27017/statemachinejoint';
validateConfig(config);
module.exports = config;
